/**
 * Public Privacy Policy — sits OUTSIDE the (app) auth-gated route group so
 * anonymous visitors (SnapTrade reviewers, prospective users) can reach it
 * without a login. Static server component — no client JS needed.
 *
 * This is a plain-language starting point that reflects what the app actually
 * does (accounts, SnapTrade broker connections, trade mirroring, email/SMS
 * notifications). Have it reviewed by counsel before relying on it — it is not
 * legal advice.
 */
import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — Kopyya",
  description: "How Kopyya collects, uses, and protects your information.",
};

const UPDATED = "July 2026";
const SUPPORT_EMAIL = "support@kopyya.com";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-semibold mb-2" style={{ color: "var(--text)" }}>{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed" style={{ color: "var(--text-2)" }}>
        {children}
      </div>
    </section>
  );
}

function Bullets({ items }: { items: string[] }) {
  return (
    <ul className="list-disc pl-5 space-y-1.5">
      {items.map((t, i) => <li key={i}>{t}</li>)}
    </ul>
  );
}

export default function PrivacyPage() {
  return (
    <main className="relative min-h-screen" style={{ background: "var(--bg)", color: "var(--text)" }}>
      {/* Top bar — brand + back to home */}
      <header className="px-6 sm:px-10 py-6 flex items-center justify-between border-b" style={{ borderColor: "var(--border)" }}>
        <Link href="/" className="text-base font-semibold tracking-tight no-underline" style={{ color: "var(--text)" }}>
          Kopyya
        </Link>
        <Link href="/" className="text-sm no-underline" style={{ color: "var(--muted)" }}>
          ← Back to home
        </Link>
      </header>

      <div className="mx-auto max-w-3xl px-6 sm:px-8 py-10">
        <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
        <p className="mt-2 text-sm" style={{ color: "var(--muted)" }}>Last updated: {UPDATED}</p>

        <p className="mt-6 text-sm leading-relaxed" style={{ color: "var(--text-2)" }}>
          Kopyya (&quot;Kopyya&quot;, &quot;we&quot;, &quot;us&quot;) provides a copy-trading platform that lets
          subscribers automatically mirror a trader&apos;s orders through their own connected brokerage account.
          This policy explains what information we collect, how we use and share it, and the choices you have.
          It applies to kopyya.com and the Kopyya application.
        </p>

        <Section title="1. Information we collect">
          <p>We collect information you provide and information generated as you use the service:</p>
          <Bullets items={[
            "Account information — your name, email address, phone number (if you enable SMS), role (trader or subscriber), and a securely hashed password. We never store your password in plain text.",
            "Brokerage connection data — when you connect a brokerage, the connection is established through SnapTrade. We receive and store encrypted access tokens that let us place and read orders on your behalf. We do NOT receive or store your brokerage username or password.",
            "Trading data — the orders, fills, positions, and profit-and-loss generated by your account, and (for subscribers) the trades mirrored from the trader you follow.",
            "Preferences — your copy settings (multipliers, limits, filters) and notification preferences.",
            "Technical and usage data — IP address, device/browser information, log data, and cookies used to keep you signed in and to secure the service.",
          ]} />
        </Section>

        <Section title="2. How we use your information">
          <Bullets items={[
            "To operate the service — authenticate you, connect your brokerage, and mirror trades according to your settings.",
            "To send notifications you ask for — order and account alerts by in-app notification, email, and (if you opt in) SMS.",
            "To provide support and respond to your requests.",
            "To secure the platform — detect, prevent, and investigate fraud, abuse, and security incidents.",
            "To comply with legal and regulatory obligations.",
          ]} />
        </Section>

        <Section title="3. Brokerage connections and SnapTrade">
          <p>
            We connect to your brokerage through <strong>SnapTrade</strong>, a third-party brokerage-connectivity
            provider. When you link an account, SnapTrade handles the brokerage login; your brokerage credentials
            are entered with SnapTrade / your broker, not with Kopyya, and are never visible to us. We store only
            the encrypted authorization needed to place and read orders. You can disconnect a brokerage at any time
            from the Broker page, which revokes that authorization.
          </p>
        </Section>

        <Section title="4. How we share information">
          <p>We share information only as needed to run the service. We do not sell your personal information.</p>
          <Bullets items={[
            "SnapTrade — to establish and maintain your brokerage connection and route orders.",
            "Your brokerage — to place, modify, cancel, and read the orders and positions in your account.",
            "Service providers — email delivery (SendGrid), SMS delivery (Twilio) if you opt in, and cloud hosting/infrastructure, each acting on our behalf under confidentiality obligations.",
            "For copy-trading — a subscriber's aggregate performance may be visible to the trader they follow (and to platform administrators) to operate and support copy relationships. Your brokerage login is never shared.",
            "Legal and safety — when required by law, or to protect the rights, property, or safety of Kopyya, our users, or others.",
          ]} />
        </Section>

        <Section title="5. Data security">
          <p>
            We protect data in transit with TLS and encrypt sensitive stored data — including brokerage
            authorization tokens — at rest. Access to production systems is restricted. No method of transmission
            or storage is completely secure, but we work to protect your information and to respond promptly to any
            issue.
          </p>
        </Section>

        <Section title="6. Data retention">
          <p>
            We keep your information for as long as your account is active and as needed to provide the service,
            comply with legal obligations, resolve disputes, and enforce our agreements. When you close your account
            we delete or de-identify your personal information, except where retention is required by law.
          </p>
        </Section>

        <Section title="7. Your choices and rights">
          <Bullets items={[
            "Access and correction — view and update your profile (name, email, phone) in Settings.",
            "Notifications — turn email/SMS notifications on or off in Settings; standard message rates may apply to SMS.",
            "Brokerage — disconnect a brokerage at any time from the Broker page.",
            "Deletion — request deletion of your account and personal data by contacting us.",
          ]} />
          <p>
            Depending on where you live, you may have additional rights (such as access, correction, deletion, or
            portability). To exercise any of these, contact us at{" "}
            <a href={`mailto:${SUPPORT_EMAIL}`} style={{ color: "var(--accent)" }}>{SUPPORT_EMAIL}</a>.
          </p>
        </Section>

        <Section title="8. Cookies">
          <p>
            We use a secure, http-only session cookie to keep you signed in and to protect against cross-site
            request forgery. We do not use advertising cookies.
          </p>
        </Section>

        <Section title="9. Children">
          <p>
            Kopyya is not directed to individuals under 18, and we do not knowingly collect information from
            children. If you believe a child has provided us information, contact us and we will delete it.
          </p>
        </Section>

        <Section title="10. Not financial advice">
          <p>
            Kopyya is a technology platform for mirroring trades you choose to follow. It does not provide
            investment, financial, tax, or legal advice, and it does not recommend any security or strategy. Trading
            involves risk, including the possible loss of principal. You are responsible for your own decisions.
          </p>
        </Section>

        <Section title="11. Changes to this policy">
          <p>
            We may update this policy from time to time. When we do, we will revise the &quot;Last updated&quot;
            date above and, for material changes, provide a more prominent notice.
          </p>
        </Section>

        <Section title="12. Contact us">
          <p>
            Questions about this policy or your data? Email us at{" "}
            <a href={`mailto:${SUPPORT_EMAIL}`} style={{ color: "var(--accent)" }}>{SUPPORT_EMAIL}</a>.
          </p>
        </Section>

        <div className="mt-10 pt-6 border-t text-xs" style={{ borderColor: "var(--border)", color: "var(--muted)" }}>
          © {new Date().getFullYear()} Kopyya. All rights reserved.
        </div>
      </div>
    </main>
  );
}
