"""add_symbol_filters_to_subscriber_settings

Revision ID: ee96be9de3fb
Revises: 33ee68c24d53
Create Date: 2026-05-31 11:00:23.377900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ee96be9de3fb'
down_revision: Union[str, None] = '33ee68c24d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber_settings', sa.Column('symbol_exclusion_list', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('subscriber_settings', sa.Column('symbol_inclusion_list', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber_settings', 'symbol_inclusion_list')
    op.drop_column('subscriber_settings', 'symbol_exclusion_list')
    # ### end Alembic commands ###
