"""add_daily_profit_limit_and_auto_resume

Revision ID: faca94c189a1
Revises: ee96be9de3fb
Create Date: 2026-05-31 14:32:14.687362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'faca94c189a1'
down_revision: Union[str, None] = 'ee96be9de3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber_settings', sa.Column('daily_profit_limit', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('subscriber_settings', sa.Column('pnl_auto_paused_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber_settings', 'pnl_auto_paused_at')
    op.drop_column('subscriber_settings', 'daily_profit_limit')
    # ### end Alembic commands ###
